CREATE TABLE `props_plans` (
    `id`          TEXT PRIMARY KEY,
    `name`        TEXT NOT NULL,
    `price`       TEXT NOT NULL,
    `frequency`   TEXT NOT NULL,
    `description` TEXT NOT NULL,
    `features`    TEXT NOT NULL,   -- JSON array of strings
    `sort_order`  INTEGER NOT NULL,
    `active`      INTEGER DEFAULT 1
);

INSERT INTO props_plans (id, name, price, frequency, description, features, sort_order, active) VALUES
('done_for_you',
 'Done for You',
 '35',
 '/mo',
 'Perfect for landlords who want a fully managed solution.',
 '["Full system access","Automated communications","Payment tracking","Regular updates"]',
 1, 1),
('done_with_you',
 'Done with You',
 '2700',
 '/one-time',
 'Ideal for landlords who want initial setup assistance.',
 '["Full system access","Personalized setup assistance","Data migration","Training sessions"]',
 2, 1),
('done_by_you',
 'Done by You',
 '950',
 '/installation',
 'For hands-on landlords who want full control.',
 '["System installation","Basic configuration","Documentation","Pay-per-hour support"]',
 3, 1),
('crowdfunding',
 'Support Our Development',
 '370',
 '/one-time',
 'Lifetime contribution — get lifetime access to all current and future features.',
 '["Lifetime access","All current features","All future features"]',
 4, 1);
